version: '3.4'

services:
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'iulian89'
    volumes:
      - data:/var/lib/postgresql/data
  server: 
    build: .
    ports: 
      - '5000:5000'
  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
volumes: 
  data: 